"use client"

import { useState, useEffect } from "react"
import { Check, ChevronRight, ChevronDown, Download } from "lucide-react"

type AppState = "idle" | "scanning" | "results"
type StepStatus = "pending" | "active" | "complete"

interface ScanStep {
  id: number
  label: string
  status: StepStatus
}

interface TreeNode {
  path: string
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"
  children?: TreeNode[]
  expanded?: boolean
}

interface Vulnerability {
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"
  endpoint: string
  type: string
  description: string
}

const SCAN_STEPS: ScanStep[] = [
  { id: 1, label: "JS File Crawling", status: "pending" },
  { id: 2, label: "Swagger Detection", status: "pending" },
  { id: 3, label: "Endpoint Discovery", status: "pending" },
  { id: 4, label: "Attack Simulation", status: "pending" },
  { id: 5, label: "Generating Report", status: "pending" },
]

const MOCK_API_MAP: TreeNode[] = [
  {
    path: "/users/v1",
    severity: "LOW",
    expanded: true,
    children: [
      { path: "/admin", severity: "CRITICAL" },
      { path: "/_debug", severity: "CRITICAL" },
    ],
  },
  { path: "/books/v1", severity: "LOW" },
  { path: "/openapi.json", severity: "HIGH" },
]

const MOCK_VULNERABILITIES: Vulnerability[] = [
  {
    severity: "CRITICAL",
    endpoint: "/users/v1/admin",
    type: "AUTH RISK",
    description: "Accessible without authentication",
  },
  {
    severity: "CRITICAL",
    endpoint: "/users/v1/_debug",
    type: "DATA EXPOSURE",
    description: "Exposes plaintext passwords",
  },
  {
    severity: "HIGH",
    endpoint: "/openapi.json",
    type: "INFO DISCLOSURE",
    description: "API docs publicly accessible",
  },
  {
    severity: "HIGH",
    endpoint: "/users/v1",
    type: "RATE LIMIT",
    description: "No rate limiting detected",
  },
  {
    severity: "MEDIUM",
    endpoint: "/users/v1/_debug",
    type: "AUTH RISK",
    description: "Debug endpoint exposed in production",
  },
]

const AI_REPORT = `Security Assessment Report — Generated by ShadowScan

Executive Summary: The target application exhibits several critical security vulnerabilities that require immediate attention. Our automated scan identified 7 unique API endpoints, with 5 containing security issues ranging from medium to critical severity. The overall risk score of 85/100 indicates a high-risk posture that should be addressed before production deployment.

Critical Findings: The most severe issues were discovered in the /users/v1/admin and /users/v1/_debug endpoints. The admin panel lacks any form of authentication middleware, allowing unauthenticated users to access sensitive administrative functions. Additionally, the debug endpoint was found to expose user credentials in plaintext format, which represents a severe data protection violation and potential compliance issue under GDPR and CCPA regulations.

API Documentation Exposure: The OpenAPI specification file at /openapi.json is publicly accessible without authentication. While API documentation can be beneficial for developers, exposing it publicly reveals the complete attack surface of your application, including internal endpoints, parameter structures, and authentication mechanisms. This information significantly reduces the effort required for malicious actors to identify and exploit vulnerabilities.

Recommendations: Implement authentication middleware across all sensitive endpoints immediately. Remove or restrict access to the debug endpoint in production environments. Configure rate limiting on all public-facing endpoints to prevent brute force and denial of service attacks. Move API documentation behind authentication or restrict access to authorized development teams only. Consider implementing a Web Application Firewall (WAF) for additional protection against common attack vectors.`

function getSeverityColor(severity: string) {
  switch (severity) {
    case "CRITICAL":
      return "bg-red-500"
    case "HIGH":
      return "bg-orange-500"
    case "MEDIUM":
      return "bg-yellow-500"
    case "LOW":
      return "bg-emerald-500"
    default:
      return "bg-zinc-500"
  }
}

function getSeverityBorder(severity: string) {
  switch (severity) {
    case "CRITICAL":
      return "border-l-red-500"
    case "HIGH":
      return "border-l-orange-500"
    case "MEDIUM":
      return "border-l-yellow-500"
    case "LOW":
      return "border-l-emerald-500"
    default:
      return "border-l-zinc-500"
  }
}

function TreeNodeComponent({
  node,
  depth = 0,
  onToggle,
}: {
  node: TreeNode
  depth?: number
  onToggle: (path: string) => void
}) {
  const hasChildren = node.children && node.children.length > 0
  const isExpanded = node.expanded

  return (
    <div className="select-none">
      <div
        className={`flex items-center gap-2 py-1.5 px-2 rounded cursor-pointer transition-colors hover:bg-zinc-800/50 ${depth > 0 ? "ml-4" : ""}`}
        onClick={() => hasChildren && onToggle(node.path)}
      >
        {hasChildren ? (
          isExpanded ? (
            <ChevronDown className="w-3.5 h-3.5 text-zinc-500" />
          ) : (
            <ChevronRight className="w-3.5 h-3.5 text-zinc-500" />
          )
        ) : (
          <span className="w-3.5" />
        )}
        <span className="font-mono text-sm text-zinc-300">{node.path}</span>
        <span
          className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${getSeverityColor(node.severity)} text-white`}
        >
          {node.severity}
        </span>
      </div>
      <div
        className={`overflow-hidden transition-all duration-200 ${isExpanded ? "max-h-96" : "max-h-0"}`}
      >
        {hasChildren && (
          <div className="relative ml-4 pl-2 border-l border-zinc-700">
            {node.children?.map((child, idx) => (
              <TreeNodeComponent key={idx} node={child} depth={depth + 1} onToggle={onToggle} />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export default function ShadowScan() {
  const [appState, setAppState] = useState<AppState>("idle")
  const [targetUrl, setTargetUrl] = useState("")
  const [steps, setSteps] = useState<ScanStep[]>(SCAN_STEPS)
  const [apiMap, setApiMap] = useState<TreeNode[]>(MOCK_API_MAP)
  const [fadeIn, setFadeIn] = useState(true)
  const [scanResults, setScanResults] = useState<any>(null)

  const startScan = async () => {
    if (!targetUrl.trim()) return
    setFadeIn(false)
    setTimeout(async () => {
      setAppState("scanning")
      setSteps(SCAN_STEPS.map((s) => ({ ...s, status: "pending" })))
      setFadeIn(true)

      try {
        const response = await fetch("http://127.0.0.1:8000/scan", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ target: targetUrl }),
        })
        const data = await response.json()
        setScanResults(data)
        setFadeIn(false)
        setTimeout(() => {
          setAppState("results")
          setFadeIn(true)
        }, 200)
      } catch (err) {
        console.error("Scan failed", err)
      }
    }, 200)
  }

  useEffect(() => {
    if (appState !== "scanning") return

    let currentStep = 0
    const interval = setInterval(() => {
      if (currentStep < SCAN_STEPS.length) {
        setSteps((prev) =>
          prev.map((step, idx) => {
            if (idx === currentStep) return { ...step, status: "active" }
            if (idx < currentStep) return { ...step, status: "complete" }
            return step
          })
        )
        currentStep++
      } else {
        clearInterval(interval)
        setSteps((prev) => prev.map((step) => ({ ...step, status: "complete" })))
      }
    }, 800)

    return () => clearInterval(interval)
  }, [appState])

  const toggleNode = (path: string) => {
    setApiMap((prev) =>
      prev.map((node) => (node.path === path ? { ...node, expanded: !node.expanded } : node))
    )
  }

  const downloadReport = () => {
    const content = scanResults?.ai_report ?? AI_REPORT
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "shadowscan-report.txt"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-zinc-100">
      {/* IDLE STATE */}
      {appState === "idle" && (
        <div
          className={`min-h-screen flex flex-col items-center justify-center px-4 transition-opacity duration-200 ${fadeIn ? "opacity-100" : "opacity-0"}`}
        >
          <h1 className="text-5xl font-semibold tracking-tight text-white mb-3">ShadowScan</h1>
          <p className="text-zinc-500 text-lg mb-10">Automated API security reconnaissance</p>
          <div className="flex w-full max-w-xl gap-3">
            <input
              type="text"
              value={targetUrl}
              onChange={(e) => setTargetUrl(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && startScan()}
              placeholder="https://target-api.com"
              className="flex-1 bg-transparent border border-zinc-800 rounded-md px-4 py-3 text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-zinc-600 transition-colors font-mono text-sm"
            />
            <button
              onClick={startScan}
              className="px-6 py-3 bg-[#00C9A7] text-[#0a0a0a] font-medium rounded-md hover:bg-[#00b396] transition-colors"
            >
              Scan
            </button>
          </div>
        </div>
      )}

      {/* SCANNING STATE */}
      {appState === "scanning" && (
        <div
          className={`min-h-screen transition-opacity duration-200 ${fadeIn ? "opacity-100" : "opacity-0"}`}
        >
          <div className="border-b border-zinc-800 px-6 py-4">
            <div className="max-w-xl mx-auto flex gap-3">
              <input
                type="text"
                value={targetUrl}
                readOnly
                className="flex-1 bg-transparent border border-zinc-800 rounded-md px-4 py-2 text-zinc-400 font-mono text-sm"
              />
              <button
                disabled
                className="px-5 py-2 bg-zinc-800 text-zinc-500 font-medium rounded-md cursor-not-allowed"
              >
                Scanning...
              </button>
            </div>
          </div>
          <div className="max-w-md mx-auto mt-24 px-4">
            <div className="space-y-0">
              {steps.map((step, idx) => (
                <div key={step.id} className="flex items-start gap-4 relative">
                  <div className="flex flex-col items-center">
                    <div
                      className={`w-3 h-3 rounded-full flex items-center justify-center transition-all duration-300 ${
                        step.status === "complete"
                          ? "bg-[#00C9A7]"
                          : step.status === "active"
                            ? "bg-[#00C9A7] animate-pulse"
                            : "bg-zinc-700"
                      }`}
                    >
                      {step.status === "complete" && <Check className="w-2 h-2 text-[#0a0a0a]" />}
                    </div>
                    {idx < steps.length - 1 && (
                      <div
                        className={`w-px h-10 transition-colors duration-300 ${step.status === "complete" ? "bg-[#00C9A7]" : "bg-zinc-800"}`}
                      />
                    )}
                  </div>
                  <span
                    className={`text-sm pt-0 transition-colors duration-300 ${
                      step.status === "complete"
                        ? "text-zinc-300"
                        : step.status === "active"
                          ? "text-white"
                          : "text-zinc-600"
                    }`}
                  >
                    {step.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* RESULTS STATE */}
      {appState === "results" && (
        <div
          className={`min-h-screen transition-opacity duration-200 ${fadeIn ? "opacity-100" : "opacity-0"}`}
        >
          {/* Stats Bar */}
          <div className="sticky top-0 z-10 bg-[#0a0a0a] border-b border-zinc-800 px-6 py-4">
            <div className="max-w-6xl mx-auto flex gap-6">
              <div className="flex-1 text-center">
                <div className="text-3xl font-semibold text-white">{scanResults?.endpoints_found ?? 7}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wide">Endpoints</div>
              </div>
              <div className="w-px bg-zinc-800" />
              <div className="flex-1 text-center">
                <div className="text-3xl font-semibold text-white">{scanResults?.vulnerabilities_count ?? 5}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wide">Vulnerabilities</div>
              </div>
              <div className="w-px bg-zinc-800" />
              <div className="flex-1 text-center">
                <div className="text-3xl font-semibold text-red-400">{scanResults?.risk_score ?? 85}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wide">Risk Score</div>
              </div>
            </div>
          </div>

          {/* Two Column Body */}
          <div className="max-w-6xl mx-auto px-6 py-8">
            <div className="grid grid-cols-1 lg:grid-cols-[38%_62%] gap-8">
              {/* API Map */}
              <div>
                <h3 className="text-[10px] uppercase tracking-widest text-zinc-500 mb-4 font-medium">
                  API Map
                </h3>
                <div className="bg-zinc-900/50 rounded-lg p-4 border border-zinc-800">
                  {apiMap.map((node, idx) => (
                    <TreeNodeComponent key={idx} node={node} onToggle={toggleNode} />
                  ))}
                </div>
              </div>

              {/* Vulnerabilities */}
              <div>
                <h3 className="text-[10px] uppercase tracking-widest text-zinc-500 mb-4 font-medium">
                  Vulnerabilities
                </h3>
                <div className="space-y-2">
                  {(scanResults?.vulnerabilities ?? MOCK_VULNERABILITIES).map((vuln: Vulnerability, idx: number) => (
                    <div
                      key={idx}
                      className={`flex items-center gap-4 p-3 bg-zinc-900/50 rounded-lg border border-zinc-800 border-l-2 ${getSeverityBorder(vuln.severity)} hover:bg-zinc-800/50 transition-colors cursor-default`}
                    >
                      <span className="font-mono text-sm text-zinc-300 min-w-[140px]">
                        {vuln.endpoint}
                      </span>
                      <span
                        className={`text-[10px] font-medium px-2 py-0.5 rounded ${getSeverityColor(vuln.severity)} text-white whitespace-nowrap`}
                      >
                        {vuln.type}
                      </span>
                      <span className="text-sm text-zinc-500 flex-1">{vuln.description}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* AI Report */}
            <div className="mt-12 pt-8 border-t border-zinc-800">
              <h3 className="text-[10px] uppercase tracking-widest text-zinc-500 mb-4 font-medium">
                AI Analysis
              </h3>
              <div className="font-mono text-sm text-zinc-500 leading-relaxed whitespace-pre-wrap">
                {scanResults?.ai_report ?? AI_REPORT}
              </div>
            </div>

            {/* Download Button */}
            <div className="flex justify-end mt-8 pb-8">
              <button
                onClick={downloadReport}
                className="flex items-center gap-2 px-4 py-2 border border-[#00C9A7] text-[#00C9A7] rounded-md hover:bg-[#00C9A7]/10 transition-colors"
              >
                <Download className="w-4 h-4" />
                Download Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}